myonlineshop/myonlineshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls'), name='main'),  # Include your app's URLs
    # ... other URL patterns ...
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myonlineshop/shop/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView, product_create, register, user_login, user_logout, CartView, AddToCartView, RemoveFromCartView, user_profile

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('product/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('product_create/', product_create, name='product_create'),
    path('register/', register, name='register'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<int:product_id>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<int:product_id>/', RemoveFromCartView.as_view(), name='remove_from_cart'),
    path('user_profile/', user_profile, name='profile'),
]

myonlineshop/shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
class Product(models.Model):
    CATEGORY_CHOICES = [
        ('Pants', 'Pants'),
        ('Jacket', 'Jacket'),
        ('Sweatshirts & Hoodies', 'Sweatshirts & Hoodies'),
        ('Shoes', 'Shoes'),
        ('Polo', 'Polo'),
        ('T-Shirt', 'T-Shirt'),
        ('Denim', 'Denim'),
        ('Shorts', 'Shorts')
        # Add more categories as needed
    ]

    SIZE_CHOICES = [
        ('KIDS', 'Kids'),
        ('XS', 'Extra Small'),
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
        ('XXL', 'Double Extra Large'),
        # Add more sizes as needed
    ]
    AUCTION_TYPE_CHOICES = [
        ('sell', 'Sell'),
        ('auction', 'Auction'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.CharField(max_length=100, choices=CATEGORY_CHOICES, null=True)
    size = models.CharField(max_length=5, choices=SIZE_CHOICES, null=True)
    tags = models.CharField(max_length=200, blank=True, null=True)
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    outseam = models.CharField(max_length=10, blank=True, null=True)
    inseam = models.CharField(max_length=10, blank=True, null=True)
    waist = models.CharField(max_length=10, blank=True, null=True)
    bottom = models.CharField(max_length=10, blank=True, null=True)
    chest = models.CharField(max_length=10, blank=True, null=True)
    length = models.CharField(max_length=10, blank=True, null=True)
    sleeve = models.CharField(max_length=10, blank=True, null=True)
    start_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    auction_type = models.CharField(
        max_length=10,
        choices=AUCTION_TYPE_CHOICES,
        default='sell',
    )

    def __str__(self):
        return self.name

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images/')

    def __str__(self):
        return f"Image for {self.product.name}"
class CustomUser(AbstractUser):
    birth_date = models.DateField(blank=True, null=True)
    profile_picture = models.ImageField(blank=True, null=True, upload_to='profile_pics/')

class Cart(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartItem')

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)


    def total_price(self):
        return self.quantity * self.product.price

class Auction(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, null=True, blank=True)
    auction_type = models.CharField(max_length=10, choices=[('sell', 'Sell'), ('auction', 'Auction')])

    def __str__(self):
        return f"Auction for {self.product.name}"

class AuctionBid(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    bid_amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Bid of ${self.bid_amount} by {self.user.username}"

# Create your models here.

myonlineshop/shop/forms.py
from django import forms
from .models import Product, CustomUser, ProductImage, AuctionBid
from django.contrib.auth.forms import UserCreationForm

class AuctionBidForm(forms.ModelForm):
    class Meta:
        model = AuctionBid
        fields = ['bid_amount']
class ProductForm(forms.ModelForm):
    tags = forms.CharField(max_length=200, required=False)
    auction_type = forms.ChoiceField(choices=Product.AUCTION_TYPE_CHOICES)

    def clean_tags(self):
        tags = self.cleaned_data.get('tags')
        if tags and not tags.startswith('#'):
            raise forms.ValidationError('Tags must start with "#"')
        return tags

    class Meta:
        model = Product
        fields = ['name', 'description', 'start_bid', 'price','category', 'size', 'image',
                  'outseam', 'inseam', 'waist', 'bottom', 'chest', 'length', 'sleeve', 'auction_type', 'quantity']


class ProductImageForm(forms.ModelForm):
    class Meta:
        model = ProductImage
        fields = ['image']

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'birth_date', 'profile_picture')

myonlineshop/shop/views.py
from django.views.generic import ListView, DetailView, TemplateView, RedirectView, View
from .models import Product, Cart, CartItem, ProductImage, AuctionBid, Auction
from django.urls import reverse_lazy, reverse
from .forms import ProductForm, CustomUserCreationForm, ProductImageForm, AuctionBidForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum, Q
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required
import logging
from django.contrib import messages
logger = logging.getLogger(__name__)


class ProductListView(ListView):
    model = Product
    template_name = 'shop/product_list.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = Product.objects.all()

        # Filter by name or tags
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(
                Q(name__icontains=query) | Q(tags__icontains=query)
            )

        # Filtering by price range
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')
        if min_price:
            queryset = queryset.filter(price__gte=min_price)
        if max_price:
            queryset = queryset.filter(price__lte=max_price)

        # Filter by category
        category = self.request.GET.get('category')
        if category:
            queryset = queryset.filter(category__iexact=category)

        # Filter by size
        size = self.request.GET.get('size')
        if size:
            queryset = queryset.filter(size=size)

        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        cart_items = cart.cartitem_set.annotate(total_price=Sum('quantity'))
        total_quantity = cart_items.aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0
        context['total_quantity'] = total_quantity
        return context


class ProductDetailView(View):
    template_name = 'shop/product_detail.html'

    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        bid_form = AuctionBidForm()

        highest_bid = None
        if product.auction_type == 'auction':
            auction = Auction.objects.get(product=product)
            highest_bid = AuctionBid.objects.filter(auction=auction).order_by('-bid_amount').first()
        return render(request, self.template_name, {
            'product': product,
            'bid_form': bid_form,
            'highest_bid': highest_bid
        })

    def post(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        bid_form = AuctionBidForm(request.POST)

        if bid_form.is_valid():
            if product.auction_type == 'auction':
                auction = Auction.objects.get(product=product)
                new_bid = bid_form.save(commit=False)
                new_bid.user = request.user
                new_bid.auction = auction
                new_bid.save()
                return redirect('product_detail', pk=pk)

        return render(request, self.template_name, {
            'product': product,
            'bid_form': bid_form,
        })
@login_required
def product_create(request):
    ProductImageFormSet = inlineformset_factory(Product, ProductImage, form=ProductImageForm, extra=3, max_num=10)

    if request.method == 'POST':
        product_form = ProductForm(request.POST, request.FILES)
        formset = ProductImageFormSet(request.POST, request.FILES)

        if product_form.is_valid() and formset.is_valid():
            product = product_form.save(commit=False)
            product.user = request.user

            # Handling auction details
            auction_type = product_form.cleaned_data['auction_type']
            if auction_type == 'auction':
                start_bid = product_form.cleaned_data['start_bid']
                product.start_bid = start_bid



            product.save()  # Save the product first

            if auction_type == 'auction':
                # Create an associated Auction object after the product is saved
                auction = Auction.objects.create(product=product, auction_type=auction_type)

            formset.instance = product
            formset.save()

            logger.info(f"Product created: {product.name} (ID: {product.id})")
            return redirect('product_list')
        else:
            logger.error(f"Product creation failed. Form errors: {product_form.errors}, {formset.errors}")
    else:
        product_form = ProductForm()
        formset = ProductImageFormSet()

    product_id = None
    if product_form.instance and product_form.instance.id:
        product_id = product_form.instance.id

    return render(request, 'shop/product_create.html',
                  {'product_form': product_form, 'formset': formset, 'product_id': product_id})

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('product_list')  # Redirect to your home page
    return render(request, 'registration/login.html')

def user_logout(request):
    logout(request)
    return redirect('login')


class CartView(TemplateView):
    template_name = 'shop/cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        cart_items = cart.cartitem_set.annotate(total_price=Sum('quantity'))

        total_quantity = cart_items.aggregate(total_quantity=Sum('quantity'))['total_quantity'] or 0

        context['cart'] = cart
        context['cart_items'] = cart_items
        context['total_quantity'] = total_quantity
        return context

class RemoveFromCartView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        product_id = self.kwargs['product_id']
        product = Product.objects.get(pk=product_id)
        cart = Cart.objects.get(user=self.request.user)
        cart_item = CartItem.objects.get(cart=cart, product=product)
        if cart_item.quantity > 1:
                cart_item.quantity -= 1
                cart_item.save()
        else:
            cart_item.delete()
        return reverse('cart')

class AddToCartView(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        product_id = kwargs['product_id']
        product = Product.objects.get(pk=product_id)
        cart, created = Cart.objects.get_or_create(user=self.request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        if not created and product.quantity > cart_item.quantity:
            cart_item.quantity += 1
            cart_item.save()
            return reverse('cart')
        else:
            messages.error(self.request,'There are only {{ product.quantity }} items in stock')
            return reverse('cart')


@login_required
def user_profile(request):
    user_products = Product.objects.filter(user=request.user)
    return render(request, 'shop/user_profile.html', {'user_products': user_products})

def auction_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    # Assuming there's a foreign key from AuctionBid to Product for bids
    current_bid = AuctionBid.objects.filter(product=product).order_by('-bid_amount').first()
    return render(request, 'auction_detail.html', {'product': product, 'current_bid': current_bid})
# Create your views here.

myonlineshop/shop/templates/shop/auction_detail.html
{% extends 'base_generic.html' %}

{% block content %}
<h2>{{ product.name }}</h2>
{% for image in product.productimage_set.all %}
    <img src="{{ image.image.url }}" alt="{{ product.name }} Image">
{% endfor %}
<p>{{ product.description }}</p>

{% if current_bid %}
    <p>Current Bid: ${{ current_bid.bid_amount }}</p>
    <p>Bidder: {{ current_bid.user.username }}</p>
{% else %}
    <p>No bids yet</p>
{% endif %}
{% endblock %}

myonlineshop/shop/templates/shop/cart.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
<div class="store-container">
  <h1>Your Cart</h1>
  <p class="cart_total_quantity">Items in total: {{ total_quantity }}</p>
  {% for item in cart.cartitem_set.all %}
    <div class="cart_product">
            {% with product_image=item.product.productimage_set.first %}
        {% if product_image %}
          <img class="product_cartimg"src="{{ product_image.image.url }}" alt="{{ item.product.name }} Image">
        {% else %}
          <!-- Display a placeholder image if no images are available -->
          <img src="{% static 'placeholder_image.png' %}" alt="Placeholder Image">
        {% endif %}
      {% endwith %}
      <a class="cart_product_detail_link" href="{% url 'product_detail' item.product.id  %}">
      <div class="cart_product_info">
      <h3 class="cart_product_name">{{ item.product.name }}</h3>
      <p>{{ item.product.description }}</p>
        <p>Type: {{ item.product.auction_type }}</p>
      <p> Total: {{ item.total_price }}</p>
        <p>{% for message in messages %}
          {{ message }}
        {% endfor %}</p>
      </div>
      </a>
      <div class="cart_quantity_change">
      <a class="cart_remove_item"href="{% url 'remove_from_cart' product_id=item.product.id %}">-</a>
      <p class="cart_item_quantity">{{ item.quantity }}</p>
      <a class="cart_add_item" href="{% url 'add_to_cart' product_id=item.product.id %}">+</a>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

myonlineshop/shop/templates/shop/product_card.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'shop/style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="product-card">
    <h3>{{ product.name }}</h3>
    <span class="price">${{ product.price }}</span>
    <p>{{ product.description }}</p>
    <!-- Display each image associated with the product -->
    {% for image in product.productimage_set.all %}
        <img src="{{ image.image.url }}" alt="{{ product.name }} Image">
    {% endfor %}
    <a href="{% url 'add_to_cart' product_id=product.id %}" class="btn">Add to Cart</a>
</div>
</body>
</html>

myonlineshop/shop/templates/shop/product_create.html
{% extends 'base_generic.html' %}

{% block content %}
  <h2>Add a New Product</h2>

  <form class="product-form" method="post" action="{% url 'product_create' %}" enctype="multipart/form-data">
    {% csrf_token %}
       <input type="hidden" id="auction_type" name="auction_type" value="sell"> <!-- This field will hold the selected value -->

    <div class="form-group">
      <label>Select Sell/Auction:</label>
      <div class="btn-group" data-toggle="buttons">
        <button class="btn sell_button" id="sell">Sell</button>
        <button class="btn auction_button" id="auction">Auction</button>
      </div>
    </div>
    </div>
    </div>
    <div class="form-group">
      <label for="name">Product Name:</label>
      <input type="text" name="name" required class="form-control">
    </div>

    <div class="form-group">
      <label for="description">Description:</label>
      <textarea name="description" required class="form-control"></textarea>
    </div>

     <div class="form-group" id="price_field">
            <label for="price">Price:</label>
            <input type="number" name="price" step="0.01" required class="form-control">
        </div>
    <div class="form-group" id="auction_fields" style="display: none;">
      <label for="start_bid">Start Bid:</label>
      <input type="number" name="start_bid" id="start_bid" step="0.01" class="form-control">
    </div>
      <div class="form-group" id="quantity_field">
            <label for="quantity">Quantity:</label>
            <input type="number" name="quantity" step="1" required class="form-control">
        </div>
      <div class="form-group">
      <label for="category">Category:</label>
      <select name="category" required class="form-control">
        <option value="" selected disabled>Select Category</option>
        <option value="Pants">Pants</option>
        <option value="Jacket">Jacket</option>
        <option value="Sweatshirts & Hoodies">Sweatshirts & Hoodies</option>
        <option value="Shoes">Shoes</option>
        <option value="Polo">Polo</option>
      </select>
    </div>

    <div class="form-group">
      <label for="size">Size:</label>
      <select name="size" required class="form-control">
        <option value="" selected disabled>Select Size</option>
        <option value="XS">Extra Small</option>
        <option value="S">Small</option>
        <option value="M">Medium</option>
        <option value="L">Large</option>
        <option value="XL">Extra Large</option>
        <option value="XXL">Double Extra Large</option>
        <!-- Add more options as needed -->
      </select>
    </div>
<div id="measurements" style="display: none;">
            <!-- Fields for Pants -->
            <div class="bottom_measurements">
            <label for="id_outseam">Outseam:</label>
            <input type="text" name="outseam" id="id_outseam">

            <label for="id_inseam">Inseam:</label>
            <input type="text" name="inseam" id="id_inseam">

            <label for="id_waist">Waist:</label>
            <input type="text" name="waist" id="id_waist">

            <label for="id_bottom">Bottom:</label>
            <input type="text" name="bottom" id="id_bottom">
            </div>
            <!-- Fields for Jacket -->
            <div class="top_measurements">
            <label for="id_chest">Chest:</label>
            <input type="text" name="chest" id="id_chest">

            <label for="id_length">Length:</label>
            <input type="text" name="length" id="id_length">

            <label for="id_sleeve">Sleeve:</label>
            <input type="text" name="sleeve" id="id_sleeve">
            </div>
            <!-- Add more fields for other categories -->
        </div>

    <div class="image-upload">
        <h2>Upload Images</h2>
        {{ formset.management_form }}
        <div class="image-forms">
            {% for form in formset %}
                <div class="image-form">
                    {{ form.as_p }}
                </div>
            {% endfor %}
        </div>
        <button id="add-more-images" type="button">Add More Images</button>
    </div>



    <div class="form-group">
      <label for="tags">Tags:</label>
      <input type="text" name="tags" placeholder="Add tags (comma-separated)" class="form-control">
      {% if form.tags.errors %}
        <p class="error">{{ form.tags.errors }}</p>
      {% endif %}
    </div>

    <input type="submit" value="Add Product" class="btn btn-primary">
  </form>


{% endblock %}

myonlineshop/shop/templates/shop/product_detail.html
{% extends 'base_generic.html' %}

{% block content %}
  <div class="item-card">
    <p class="item-auction-type">Type: {{ product.auction_type }}</p>
    <h1 class="item-name">{{ product.name }}</h1>
    <p class="item-category">Category: {{ product.category }}</p>
    <p class="item-size">Size: {{ product.size }}</p>
    <div class="item-slider slick-slider" id="slider">
    {% for product_image in product.productimage_set.all %}
        <img class="item-img" src="{{ product_image.image.url }}" alt="product-img">
    {% endfor %}
    </div>
    <p class="item-description">{{ product.description }}</p>
    <p class="item-price">Instant buy: {{ product.price }}</p>
       {% if product.auction_type == 'auction' %}
        <!-- Display the bid form only for auction-type products -->
        {% if highest_bid %}
            <p class="item-current-bid">Current bid: ${{ highest_bid.bid_amount }}</p>
        {% endif %}
        <form class="auction-form" method="post" action="{% url 'product_detail' product.id %}">
            {% csrf_token %}
            {{ bid_form.as_p }} <!-- Render the bid form fields -->
            <button type="submit">Place Bid</button>
        </form>
{% endif %}
    <p class="item-price">Start bid: ${{ product.start_bid }}</p>
    <p class="item-tags">Tags: {{ product.tags }}</p>
    {% if product.category == 'Pants' %}
      {% if product.outseam or product.inseam or product.waist or product.bottom %}
      <p class="item-measurements">Measurements</p>
      {% endif %}
      {% if product.outseam %}
        <p class="item-outseam">Outseam: {{ product.outseam }}</p>
      {% endif %}
      {% if product.inseam %}
        <p class="item-inseam">Inseam: {{ product.inseam }}</p>
      {% endif %}
      {% if product.waist %}
        <p class="item-waist">Waist: {{ product.waist }}</p>
      {% endif %}
      {% if product.bottom %}
        <p class="item-bottom">Bottom: {{ product.bottom }}</p>
      {% endif %}
    {% elif product.category == 'Jacket' or product.category == 'Sweatshirts & Hoodies' or product.category == 'Polo' %}
      {% if product.chest or product.length or product.sleeve %}
      <p class="item-measurements">Measurements</p>
      {% endif %}
      {% if product.chest %}
        <p class="item-chest">Chest: {{ product.chest }}</p>
      {% endif %}
      {% if product.length %}
        <p class="item-length">Length: {{ product.length }}</p>
      {% endif %}
      {% if product.sleeve %}
        <p class="item-sleeve">Sleeve: {{ product.sleeve }}</p>
      {% endif %}
    {% endif %}
    <!-- Add more conditions for other categories -->
      <a href="{% url 'add_to_cart' product.id %}" class="btn">Add to Cart</a>
  </div>
{% endblock %}

myonlineshop/shop/templates/shop/product_list.html
{% extends 'base_generic.html' %}
{% load static %}
{% block content %}
    <div class="store-container">
        <div class="user-info">
            {% if user.is_authenticated %}
                <p>Welcome, <a class='profile_link' href="{% url 'profile' %}">{{ user.username }}!</a></p>
                <div class="profile_picture {% if user.profile_picture %}show{% else %}hide{% endif %}">
                    {% if user.profile_picture %}
                        <img src="{{ user.profile_picture.url }}" alt="{{ user.username }}'s Profile Picture">
                    {% endif %}
                </div>
                <a href="{% url 'cart' %}"><img class="cart_image" src="https://avatars.mds.yandex.net/i?id=646c0e8db2969d5dacf8f0541ab792cba23eac21-9683943-images-thumbs&n=13" alt="cart_image"></a>
                <p> {{ total_quantity }} </p>
            {% else %}
                <p>Welcome to Our Store</p>
            {% endif %}
        </div>
        <div class="switch">
             <button class="btn" id="switch-view-list-btn"><img src="{% static 'list.svg'%}" alt="" class="list-img"></button>
            <button class="btn" id="switch-view-slider-btn"><img class='slider-img'src="https://cdn0.iconfinder.com/data/icons/small-v7/512/banner_carrousel_slider_images_ad_promotion-512.png" alt=""></button>
        </div>
        <div>
            <form class="search_form" method="GET" action="{% url 'product_list' %}">
            <input type="text" name="q" placeholder="Search for products">
            <button class='btn' type="submit">Search</button>
            </form>
        </div>
        <div class="product_display">
        <div class="filters">
            <h3>Filter Options</h3>
            <form method="GET" action="{% url 'product_list' %}">
                <div class="filter-option">
                    <label for="min_price">Min Price:</label>
                    <input type="number" name="min_price" id="min_price" class="filter-input">
                </div>

                <div class="filter-option">
                    <label for="max_price">Max Price:</label>
                    <input type="number" name="max_price" id="max_price" class="filter-input">
                </div>

                <div class="filter-option">
                    <label for="category">Category:</label>
                    <select name="category" id="category" class="filter-input">
                        <option value="">--Select Category--</option>
                        {% for key, value in products.model.CATEGORY_CHOICES %}
                            <option value="{{ key }}">{{ value }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="filter-option">
                    <label>Size:</label><br>
                    <div class="size_div">
                    {% for key, value in products.model.SIZE_CHOICES %}

                            <input type="checkbox" id="size_{{ key }}" name="sizes" value="{{ key }}" class="styled-checkbox">
                            <label for="size_{{ key }}" class="checkbox-label">{{ value }}</label><br>

                    {% endfor %}
                    </div>
                </div>

                <button type="submit">Apply Filters</button>
            </form>
        </div>

       <div class="product-list" id="list" style="display: none;">
    {% for product in products %}
        <div class="product-card">
            <h3>{{ product.name }}</h3>
            {% with product_image=product.productimage_set.first %}
                {% if product_image %}
                    <img src="{{ product_image.image.url }}" alt="{{ product.name }} Image">
                {% else %}
                    <!-- Display a placeholder image if no images are available -->
                    <img src="{% static 'placeholder_image.jpg' %}" alt="Placeholder Image">
                {% endif %}
            {% endwith %}
            <a href="product/{{ product.id }}/" class="btn">Read more</a>
            {% if product.auction_type == 'auction' %}
            <p>Start Bid: {{ product.start_bid }}</p>
            {% else %}
            <p>Price: ${{ product.price }}</p>
            {% endif %}
            <p>Type: {{ product.auction_type }}</p>
            <a href="{% url 'add_to_cart' product.id %}" class="btn">Add to Cart</a>
            <div class="product_user">
                <a class='profile_link' href="{% url 'profile' %}">{{ product.user.username }}!</a>
                <div class="profile_picture {% if product.user.profile_picture %}show{% else %}hide{% endif %}">
                    {% if product.user.profile_picture %}
                        <img src="{{ product.user.profile_picture.url }}" alt="{{ product.user.username }}'s Profile Picture">
                    {% endif %}
                </div>
                <!-- Add other product details or buttons as needed -->
            </div>
        </div>
    {% endfor %}
</div>
        <!-- Slider container -->
          <div class="slick-slider" id="slider">
        {% for product in products %}
        <div class="product-card">
            <h3>{{ product.name }}</h3>
            {% with product_image=product.productimage_set.first %}
                {% if product_image %}
                    <img src="{{ product_image.image.url }}" alt="{{ product.name }} Image">
                {% else %}
                    <!-- Display a placeholder image if no images are available -->
                    <img src="{% static 'placeholder_image.jpg' %}" alt="Placeholder Image">
                {% endif %}
            {% endwith %}
            <div class="product_get">
            <a href="{% url 'product_detail' product.id%}" class="btn">Read more</a>
            {% if product.auction_type == 'auction' %}
            <p>Start Bid: {{ product.start_bid }}</p>
            {% else %}
            <p>Price: ${{ product.price }}</p>
            {% endif %}
            <p>Type: {{ product.auction_type }}</p>
            <a href="{% url 'add_to_cart' product.id %}" class="btn">Add to Cart</a>
            </div>
            <div class="product_user">
                <a class='profile_link' href="{% url 'profile' %}">{{ product.user.username }}!</a>
                <div class="profile_picture {% if product.user.profile_picture %}show{% else %}hide{% endif %}">
                    {% if product.user.profile_picture %}
                        <img src="{{ product.user.profile_picture.url }}" alt="{{ product.user.username }}'s Profile Picture">
                    {% endif %}
                </div>
                <!-- Add other product details or buttons as needed -->
            </div>
        </div>
    {% endfor %}
</div>

<button class="btn" id="change-product-btn">Random Card</button>
{% endblock %}